const Courses = [
    {
        id: '1',
        title: "Web Development",
        image: require('../../../assets/web.webp'),
        description: "Web development, also known as website development, is the creation of websites and web applications that run online on a browser.",
        course1: "html",
        course2: "css",
        course3: "Javascript",
        price: 6000,
    },
    {
        id: '2',
        title: "Graphic Design",
        image: require('../../../assets/gd.png'),
        description: "Graphic design continues to cover a range of activities including creating logos. Graphic designers use images, color and typography to attract viewers.",
        course1: "Photoshop",
        course2: "Figma",
        course3: "Adobe XD",
        price: 3000,
    },
    {
        id: '3',
        title: "React Native",
        image: require('../../../assets/mobile.webp'),
        description: "React Native is an attractive framework enabling the creation of mobile applications. Provides mobile development and more efficient code sharing across iOS, Android and the web.",
        course1: "javascript",
        course2: "ReactJS",
        course3: "React-Native",
        price: 4000,
    },
    {
        id: '4',
        title: "Coding Fundamentals",
        image: require('../../../assets/code.webp'),
        description: "The basic coding concepts include variable declaration, basic control structures, data structures, object-oriented programming, debugging, and various programming tools. ",
        course1: "Javascript",
        course2: "Algorithm",
        course3: "Data Structure",
        price: 2000,
    },
    {
        id: '5',
        title: "Ui-UX Design ",
        image: require('../../../assets/ux.webp'),
        description: "UX design involves managing the user journey while UI design focuses on the actual creation of the interface of that product or service.",
        course1: "HTML",
        course2: "CSS",
        course3: "javaScript",
        price: 1000,
    },
    {
        id: '6',
        title: "Game Development",
        image: require('../../../assets/game.webp'),
        description: "Video game developers help transform games from concept to playable reality. They do this by coding visual elements, programming features, and iterative testing until the game is ready for market.",
        course1: "C",
        course2: "C++",
        course3: "C#",
        price: 2000,
    },
]

export default Courses;